"""empty message

Revision ID: bce2c68946b2
Revises: edea4a8c7101
Create Date: 2023-11-13 22:06:30.737075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce2c68946b2'
down_revision = 'edea4a8c7101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.drop_column('birth_year')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('created')
        batch_op.drop_column('climate')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('created')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
